kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: getpods-rolebinding
  namespace: app-namespace
subjects:
- kind: ServiceAccount
  name: userlogs
  apiGroup: ""
roleRef:
  kind: Role
  name: getpods
  apiGroup: ""